background_opacity .85
font_family      SauceCodePro Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
# url_color #00ff91
show_hyperlink_targets yes
underline_hyperlinks hover
#clipboard_control yes
enable_audio_bell no
cursor_shape block
shell_integration no-cursor

# BEGIN_KITTY_THEME
# Kaolin Ocean
include current-theme.conf
# END_KITTY_THEME



